### ISSUE TITLE
Recursive Schemas?

### ISSUE THREAD

**Issue by adamse** [pepeiborra/schemas#1]
Eg can we have `TypedSchema Schema` in some nice way?

**Comment by pepeiborra** [comment]
There is already a `TypedSchema Schema` value in the [`HasSchema` instance for `Schema`](https://github.com/pepeiborra/schemas/blob/master/src/Schemas.hs#L287). Is this what you were looking for ?

Schemas for recursive datatypes (such as `Schema` itself) are problematic since the `TypedSchema` language doesn't currently have a mu binder for recursive data, and therefore the schemas are infinite.
